### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by ulmer-a** [wegwart/wegwart#1]
Was not able to build the project

CMake spit out: `Conan executable not found!`

Maybe build instructions are a nice enhancement?

**Comment by ulmer-a** [comment]
When running `build.sh`:

```
+ rm -rf build
+ mkdir build
+ pushd build
~/Projects/wegwart/build ~/Projects/wegwart
+ cmake .. -DCMAKE_BUILD_TYPE=Debug
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 10.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Downloading conan.cmake from https://github.com/conan-io/cmake-conan
-- conan_check...
CMake Error at CMakeLists.txt:25 (conan_check):
  Unknown CMake command "conan_check".
```

Doesn't work. Requirements are unclear.

**Comment by ulmer-a** [comment]
Why delete build directory each time `build.sh` is run? Not necessary.

**Comment by ulmer-a** [comment]
Why delete build directory each time `build.sh` is run? Not necessary.

**Comment by wegwart** [comment]
updated readme.txt with build instructions

**Comment by ulmer-a** [comment]
Will try

**Comment by ulmer-a** [comment]
Seems to work now.

Would be nice though if there were a separate configure script that splits dependency acquisition from the actual build (e.g. a seperate `configure.sh` and `build.sh`). Where configure.sh does the things mentioned in readme.md and performs dependency checks.
